// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Technoservice.Models
{
    public partial class ShapePerformers
    {
        public int IdShapePerfomers { get; set; }
        public Guid IdUser { get; set; }
        public int IdShape { get; set; }

        public virtual Shape IdShapeNavigation { get; set; }
        public virtual Users IdUserNavigation { get; set; }
    }
}