// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Technoservice.Models
{
    public partial class Shape
    {
        public Shape()
        {
            ShapePerformers = new HashSet<ShapePerformers>();
        }

        public int IdShape { get; set; }
        public DateTime DateOfEdition { get; set; }
        public int IdEquipment { get; set; }
        public int IdTypeOfMalfunction { get; set; }
        public string ShapeDescription { get; set; }
        public Guid UserId { get; set; }
        public int IdShapeStatus { get; set; }

        public virtual Equipment IdEquipmentNavigation { get; set; }
        public virtual TypeOfMalfunction IdShapeStatus1 { get; set; }
        public virtual ShapeStatus IdShapeStatusNavigation { get; set; }
        public virtual Users User { get; set; }
        public virtual ICollection<ShapePerformers> ShapePerformers { get; set; }
    }
}