// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Technoservice.Models
{
    public partial class Specifications
    {
        public Specifications()
        {
            Equipment = new HashSet<Equipment>();
        }

        public int IdSpecification { get; set; }
        public string TitleSpecification { get; set; }
        public string DescriptionSpecification { get; set; }

        public virtual ICollection<Equipment> Equipment { get; set; }
    }
}