// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Technoservice.Models
{
    public partial class TypeOfMalfunction
    {
        public TypeOfMalfunction()
        {
            Shape = new HashSet<Shape>();
        }

        public int IdTypeOfMalfunction { get; set; }
        public string TitleTypeOfMalfunction { get; set; }
        public string DescriptionTypeOfMalfunction { get; set; }

        public virtual ICollection<Shape> Shape { get; set; }
    }
}