// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Technoservice.Models
{
    public partial class Users
    {
        public Users()
        {
            Shape = new HashSet<Shape>();
            ShapePerformers = new HashSet<ShapePerformers>();
        }

        public Guid UserId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public string UserSurname { get; set; }
        public string UserPatronymic { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public int IdRole { get; set; }

        public virtual Role IdRoleNavigation { get; set; }
        public virtual ICollection<Shape> Shape { get; set; }
        public virtual ICollection<ShapePerformers> ShapePerformers { get; set; }
    }
}